"""
Shared memory
acts as a common storage for all agents 
1. store information generated by agents.
2. Retrieve info for sub agents.
3. Remain independent of any specific agent.
4. Provide a  common mechanism for communication.
"""
from typing import Optional,Any

class SharedMemory:
    """
    shared memory accessible by every agent
    """

    def __init__(self):
        self.memory = {}

    def add(self, key: str, value:Any) -> None:
        #storing data

        self.memory[key] = value


    def get(self, key: str) -> Any:
        #get a key value from the memory
    
        return self.memory.get(key)

    def exists(self, key: str) -> bool:
        #check if key exists
        
        return key in self.memory

    def remove(self, key:str)-> None:
        self.memory.pop(key,None)

    def get_all(self) -> dict[str , None]:
        return self.memory

    def clear(self) -> None:
        #clearing the memory
        
        self.memory.clear()

    def display(self) -> None:
        #print current memory
        
        print("="*50)
        print("SHARED MEMORY")
        print("="*50)
        for key, value in self.memory.items():
            print(f"{key}")
            print(value)
            print("="*50)
    
